//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.22 at 09:36:03 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://perscholas.com/springboot/myboot/producingwebservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.events.webservices.producer;
